### ISSUE TITLE
Json Error

### ISSUE THREAD

**Issue by biorisk2** [ztizzlegaming/CSGOWinBig-SteamBot#14]
https://i.gyazo.com/d27f6c52b32a96f66dd489a6bb92d37d.png

[ Bot Albert 2015-09-22 10:06:23] SUCCESS: Offer approved, accepting.
[ Bot Albert 2015-09-22 10:06:37] SUCCESS: Offer accepted from STEAM_0:0:139051164
[ Bot Albert 2015-09-22 10:06:39] ERROR: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: n. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SteamBot.DepositTradeOfferUserHandler.OnNewTradeOffer(TradeOffer offer) in C:\Users\Tyler\Desktop\CSGOWinBig-SteamBot-master\SteamBot\DepositTradeOfferUserHandler.cs:line 182
   at SteamBot.Bot.TradeOfferRouter(TradeOffer offer) in C:\Users\Tyler\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:line 846
   at SteamTrade.TradeOffer.TradeOfferManager.SendOfferToHandler(Offer offer) in C:\Users\Tyler\Desktop\CSGOWinBig-SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 142
   at SteamTrade.TradeOffer.TradeOfferManager.GetTradeOffersSince(Int32 unixTimeStamp) in C:\Users\Tyler\Desktop\CSGOWinBig-SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 87
   at SteamTrade.TradeOffer.TradeOfferManager.GetOffers() in C:\Users\Tyler\Desktop\CSGOWinBig-SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 113
   at SteamBot.Bot.<HandleSteamMessage>b__73_13(NotificationCallback callback) in C:\Users\Tyler\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:line 685
   at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
   at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in C:\Users\Tyler\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:line 672
   at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in C:\Users\Tyler\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:line 941
[ Bot Albert 2015-09-22 10:06:39] WARN: Restarting bot...

**Comment by biorisk2** [comment]
Anything?

**Comment by ztizzlegaming** [comment]
Hey, sorry, but if you could instead send an email to support@csgowinbig.com, I would really appreciate it. I put this in the 'Troubleshooting' part of the Readme. I want to keep issues for actual bugs and issues with the code. Also, I know that there are other issues open that are not for bugs, but there are people commenting and trying to help them already, so I can't just close it just yet.

I suspect that it is something with your hosting that is causing the json parse error, possibly a warning or error getting printed out and throwing off the json parser. If you send me an email we can try to work something out.

**Comment by signedbydc** [comment]
I have the same issues, do you found any answer to this Json error?

**Comment by Memfis85** [comment]
I have it too pls someone can help ?

**Comment by TheAnthonyNL** [comment]
Add me on steam

**Comment by nvkdesign** [comment]
same issue... how to fix it please ? :)

**Comment by Sneaky2x** [comment]
same issue here :/ anyone has a fix?

**Comment by nvkdesign** [comment]
Got the same issue and my password is on the right directory...

**Comment by Xeroner** [comment]
Anyone fixed this ? Same issue..

**Comment by TheAnthonyNL** [comment]
@Xeroner  

bad password.txt directory, seems to be fixed now ;)

 :).
