### ISSUE TITLE
Error with BOT, System.Net.WebException: Unable to connect to the remote server

### ISSUE THREAD

**Issue by ImEmil** [ztizzlegaming/CSGOWinBig-SteamBot#19]
Hey guys, did just setup the bot, my website is working 100%, the erros occurs on the BOT which I have on my VPS.
Yes I did enter the Steamguardcode for the first time, probably tradeban 7 days.
But I dont think this error should occur.

Here's the log!
<code>
[CSGOALEO.COM 2015-09-28 20:37:23] DEBUG: Initializing Steam Bot...
[CSGOALEO.COM 2015-09-28 20:37:23] INFO: Connecting...
[CSGOALEO.COM 2015-09-28 20:37:23] SUCCESS: Done Loading Bot!
[CSGOALEO.COM 2015-09-28 20:37:25] DEBUG: SteamKit2.SteamClient+ConnectedCallback
[CSGOALEO.COM 2015-09-28 20:37:25] DEBUG: Connection Callback: OK
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamUser+LoggedOnCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: Logged On Callback: OK
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamUser+AccountInfoCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamApps+VACStatusCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamFriends+FriendsListCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamApps+LicenseListCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamApps+GuestPassListCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamUser+WalletInfoCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamApps+GameConnectTokensCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamUser+SessionTokenCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamClient+CMListCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamClient+ServerListCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamClient+ServerListCallback
[CSGOALEO.COM 2015-09-28 20:37:27] DEBUG: SteamKit2.SteamFriends+PersonaStateCallback
[CSGOALEO.COM 2015-09-28 20:37:28] DEBUG: SteamKit2.SteamUser+LoginKeyCallback
[CSGOALEO.COM 2015-09-28 20:37:52] WARN: Authentication failed, retrying in 2s...
[CSGOALEO.COM 2015-09-28 20:37:56] SUCCESS: User Authenticated!
[CSGOALEO.COM 2015-09-28 20:38:00] INFO: Downloading Schema...
[CSGOALEO.COM 2015-09-28 20:38:02] SUCCESS: Schema Downloaded!
[CSGOALEO.COM 2015-09-28 20:38:02] SUCCESS: Steam Bot Logged In Completely!
[CSGOALEO.COM 2015-09-28 20:38:02] DEBUG: SteamKit2.SteamUser+MarketingMessageCallback
[CSGOALEO.COM 2015-09-28 20:38:02] DEBUG: SteamKit2.SteamUser+AccountInfoCallback
[CSGOALEO.COM 2015-09-28 20:38:02] DEBUG: SteamKit2.SteamFriends+PersonaStateCallback
[CSGOALEO.COM 2015-09-28 20:41:29] DEBUG: SteamBot.SteamNotifications+NotificationCallback
[CSGOALEO.COM 2015-09-28 20:41:29] INFO: TradeOffer notification
[CSGOALEO.COM 2015-09-28 20:41:51] ERROR: URI: unknown >> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 208.64.202.85:80
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at SteamTrade.SteamWeb.Request(String url, String method, NameValueCollection data, Boolean ajax, String referer) in C:\Users\Administrator\Desktop\C#BOT\SteamTrade\SteamWeb.cs:line 85
   at SteamTrade.SteamWeb.Fetch(String url, String method, NameValueCollection data, Boolean ajax, String referer) in C:\Users\Administrator\Desktop\C#BOT\SteamTrade\SteamWeb.cs:line 26
   at SteamTrade.TradeOffer.TradeOfferWebAPI.GetActiveTradeOffers(Boolean getSentOffers, Boolean getReceivedOffers, Boolean getDescriptions, String language) in C:\Users\Administrator\Desktop\C#BOT\SteamTrade\TradeOffer\TradeOfferWebAPI.cs:line 64
   at SteamTrade.TradeOffer.TradeOfferManager.GetActiveTradeOffers() in C:\Users\Administrator\Desktop\C#BOT\SteamTrade\TradeOffer\TradeOfferManager.cs:line 38
   at SteamTrade.TradeOffer.TradeOfferManager.GetOffers() in C:\Users\Administrator\Desktop\C#BOT\SteamTrade\TradeOffer\TradeOfferManager.cs:line 121
   at SteamBot.Bot.<HandleSteamMessage>b__73_13(NotificationCallback callback) in C:\Users\Administrator\Desktop\C#BOT\SteamBot\Bot.cs:line 685
   at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
   at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in C:\Users\Administrator\Desktop\C#BOT\SteamBot\Bot.cs:line 672
   at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in C:\Users\Administrator\Desktop\C#BOT\SteamBot\Bot.cs:line 941
[CSGOALEO.COM 2015-09-28 20:42:36] DEBUG: SteamKit2.SteamUser+SessionTokenCallback
[CSGOALEO.COM 2015-09-28 20:42:45] DEBUG: Trying to shut down bot thread.
[CSGOALEO.COM 2015-09-28 20:42:45] DEBUG: SteamKit2.SteamClient+DisconnectedCallback
[CSGOALEO.COM 2015-09-28 20:42:45] WARN: Disconnected from Steam Network!
</code>

Appreaciate any help, suggestions.

**Comment by ImEmil** [comment]
To make it more clear,
its this part.

<b>"<code> ERROR: URI: unknown >> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 208.64.202.85:80 at </code>"</b>

**Comment by ztizzlegaming** [comment]
Hey, yea if you just now logged in, the Steam trade ban can mess up a lot of stuff. Wait a week and then if it doesn't work then, send me an email at support@csgowinbig.com and we'll work something out.
